export const MAINSTREAM_GENRES: Set<string> = new Set([
  // Pop
  "pop",
  "dance pop",
  "post-teen pop",
  "electropop",
  "synthpop",
  "art pop",
  "chamber pop",
  "indie pop",
  "dream pop",
  "bedroom pop",
  "hyperpop",
  "k-pop",
  "j-pop",
  "c-pop",
  "mandopop",
  "cantopop",
  "britpop",
  "europop",
  "bubblegum pop",
  "teen pop",
  "power pop",
  // Hip-Hop / Rap
  "hip hop",
  "rap",
  "trap",
  "southern hip hop",
  "east coast hip hop",
  "west coast hip hop",
  "gangster rap",
  "conscious hip hop",
  "melodic rap",
  "drill",
  "uk drill",
  "grime",
  "crunk",
  "dirty south rap",
  "mumble rap",
  "emo rap",
  "cloud rap",
  // R&B / Soul
  "r&b",
  "urban contemporary",
  "neo soul",
  "contemporary r&b",
  "soul",
  "new jack swing",
  "quiet storm",
  // Rock
  "rock",
  "classic rock",
  "album rock",
  "hard rock",
  "soft rock",
  "alternative rock",
  "indie rock",
  "punk rock",
  "pop rock",
  "post-grunge",
  "grunge",
  "emo",
  "screamo",
  "punk",
  "pop punk",
  "garage rock",
  "psychedelic rock",
  "progressive rock",
  "southern rock",
  "blues rock",
  "arena rock",
  "glam rock",
  "heartland rock",
  // Metal
  "metal",
  "heavy metal",
  "nu metal",
  "metalcore",
  "deathcore",
  "thrash metal",
  "death metal",
  "black metal",
  "progressive metal",
  "power metal",
  "symphonic metal",
  "groove metal",
  // Electronic / Dance
  "edm",
  "electronic",
  "house",
  "deep house",
  "tech house",
  "progressive house",
  "tropical house",
  "future bass",
  "dubstep",
  "drum and bass",
  "trance",
  "techno",
  "electro house",
  "big room",
  "hardstyle",
  "future house",
  "bass music",
  "complextro",
  "moombahton",
  "riddim",
  "brostep",
  // Country
  "country",
  "contemporary country",
  "country pop",
  "country rock",
  "bro-country",
  "americana",
  "outlaw country",
  "country rap",
  "red dirt",
  // Latin
  "latin",
  "reggaeton",
  "latin pop",
  "latin hip hop",
  "bachata",
  "salsa",
  "cumbia",
  "latin rock",
  "latin trap",
  "dembow",
  "merengue",
  "banda",
  "corridos",
  "norteno",
  "ranchera",
  // Folk
  "folk",
  "indie folk",
  "folk-pop",
  "folk rock",
  "singer-songwriter",
  "acoustic",
  // Jazz
  "jazz",
  "smooth jazz",
  "vocal jazz",
  "contemporary jazz",
  "jazz fusion",
  // Classical
  "classical",
  "soundtrack",
  "film score",
  "video game music",
  "orchestral",
  "opera",
  // Reggae / Caribbean
  "reggae",
  "dancehall",
  "ska",
  "dub",
  "afrobeats",
  "afropop",
  // Other mainstream
  "blues",
  "gospel",
  "funk",
  "disco",
  "new wave",
  "synth-pop",
  "adult contemporary",
  "easy listening",
  "lo-fi beats",
  "lofi hip hop",
  "chillwave",
  "vaporwave",
  "trap soul",
  "phonk",
]);
